const cheerfulCompliments = [
  "You have the brightest smile!",
  "Your energy is contagious!",
  "You make the world a happier place!",
  "Your positivity is inspiring!",
  "You're a ray of sunshine!",
  "Your laughter is music to the soul!",
  "You light up every room you walk into!",
  "Your enthusiasm is truly refreshing!",
  "You bring so much joy to those around you!",
  "Your kindness spreads like wildfire!",
  "Your optimism makes life beautiful!",
  "You have an amazing sense of humor!",
  "Your creativity is boundless!",
  "You always know how to make people laugh!",
  "Your presence makes everything feel lighter!",
  "You bring good vibes wherever you go!",
  "You're a wonderful friend to have!",
  "Your warmth makes people feel at home!",
  "You make the world a better place just by being you!",
  "Your kindness is your superpower!",
  "You make people feel valued and loved!",
  "Your energy is refreshing and uplifting!",
  "You inspire people with your cheerful nature!",
  "You're a walking source of happiness!",
  "Your spirit is full of sunshine!"
];

const comfortingCompliments = [
  "You are stronger than you think.",
  "It's okay to feel down, but remember, you're amazing.",
  "You are loved and appreciated more than you know.",
  "Even on tough days, you shine in your own way.",
  "You have a heart full of kindness.",
  "You are never alone; you are deeply cared for.",
  "Your emotions are valid, and you deserve kindness.",
  "Your strength during hard times is inspiring.",
  "You have a beautiful soul that deserves happiness.",
  "No storm lasts forever, and you will shine again.",
  "You are resilient and can overcome anything.",
  "You deserve all the love and support in the world.",
  "Even in sadness, your light shines through.",
  "You have a gentle heart that makes the world better.",
  "Your presence alone makes a difference.",
  "You are not defined by your bad days.",
  "You are doing your best, and that is enough.",
  "Your kindness touches hearts more than you realize.",
  "You are a beautiful soul, inside and out.",
  "The world is better with you in it.",
  "Your journey matters, and so do you.",
  "Even when you feel invisible, you are seen and loved.",
  "Your struggles do not define you; your strength does.",
  "You deserve love, happiness, and peace.",
  "You are worthy of all the good things life has to offer."
];

const motivationalCompliments = [
  "Your strength is unmatched!",
  "You have the power to overcome anything!",
  "You're bold, fearless, and unstoppable!",
  "Your passion drives you toward success!",
  "You always stand up for what’s right!",
  "Your fire and determination are inspiring!",
  "You turn challenges into opportunities!",
  "Your courage is truly admirable!",
  "You refuse to let obstacles define you!",
  "You are a warrior, never backing down!",
  "Your resilience is your greatest weapon!",
  "You never give up, and that’s your superpower!",
  "Your confidence commands respect!",
  "You are fierce, determined, and strong!",
  "You use your energy to fuel your ambition!",
  "You turn frustration into motivation!",
  "You have the mindset of a true leader!",
  "You stand tall even in the face of adversity!",
  "You don't just dream; you make things happen!",
  "Your determination is truly inspiring!",
  "You have the power to change the world!",
  "Your passion is what makes you unstoppable!",
  "You are a force to be reckoned with!",
  "You channel your energy into greatness!",
  "Your intensity fuels your success!"
];


const soothingCompliments = [
  "Your presence brings peace to those around you.",
  "You have a calming aura that soothes the soul.",
  "Your words are like a gentle breeze on a warm day.",
  "You radiate serenity and kindness.",
  "Your patience and wisdom are admirable.",
  "Your voice is like a soft melody of comfort.",
  "You have a heart that understands without words.",
  "Your presence feels like a warm hug.",
  "You make others feel at ease effortlessly.",
  "Your soul is as calm as a still lake.",
  "You inspire tranquility in everyone you meet.",
  "Your kindness creates a ripple effect of peace.",
  "You have the ability to turn chaos into harmony.",
  "You carry yourself with such grace and composure.",
  "You have a way of making people feel safe.",
  "Your patience is a rare and beautiful gift.",
  "You have a naturally comforting presence.",
  "Your words bring clarity and peace.",
  "You understand the power of silence and stillness.",
  "You create a sense of warmth wherever you go.",
  "Your kindness makes the world a gentler place.",
  "Your wisdom is a source of great comfort.",
  "You have the ability to heal hearts with your words.",
  "Your gentle nature makes life feel more peaceful.",
  "You bring balance and calmness to any situation."
];

const compliments = {
  cheerfulCompliments,
  comfortingCompliments,
  motivationalCompliments,
  soothingCompliments
};

  export default compliments;
  